name = "document-biometric-attendance"

main = "document-attendance/src/index.js"

compatibility_date = "2026-08-20"

compatibility_flags = [
    "nodejs_compat"
]


[assets]

directory = "./public"


[[d1_databases]]

binding = "DB"

database_name = "document-attendance"

database_id = "YOUR_D1_DATABASE_ID"


[vars]

RP_NAME = "Document Attendance"

RP_ID = "biometric.rv-rajgnsh.workers.dev"

ORIGIN = "https://biometric.rv-rajgnsh.workers.dev"
